### ISSUE TITLE
Skeleton is not displayed with models exported from Maya2glTF

### ISSUE THREAD

**Issue by ziriax** [donmccurdy/three-gltf-viewer#101]
When using the default settings, the viewer will not show the skeleton of  skinned meshes exported with Maya2glTF, using the default settings.

It seems that the trick Maya2glTF uses to handle Maya's segment scale compensation (`ssc`) is the reason, disabling it will make the skeleton appear (the trick is to split each joint into two, since to handle segment scale compensation, one needs to have a separate node to handle the inverse parent scale)

But since both result in are valid glTF files, I consider this as a bug in this viewer.

See attached two exported files, one that shows the skeleton (`ssc-off`), the other doesn't show it (`ssc-on`).

[BlendedSkinningAnim.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2170564/BlendedSkinningAnim.zip)

**Comment by donmccurdy** [comment]
These are the resulting node trees for each model:

| ssc-off | ssc-on |
|---|---|
| ![screen shot 2018-07-09 at 10 59 51 am](https://user-images.githubusercontent.com/1848368/42469340-407a1a7e-836c-11e8-8d08-76f6d127656d.png) | ![screen shot 2018-07-09 at 10 59 16 am](https://user-images.githubusercontent.com/1848368/42469348-44eea5c0-836c-11e8-8a08-6bd91edbcbbd.png) |

Notice that in the second, joints are interspaced with non-joints nodes. That joint/non-joint distinction isn't in glTF, at least not explicitly, but it does exist in three.js and I think that's the cause here... can those separate nodes be included in the `joints` list, and just have zero weights for all vertices?

A few relevant points from the spec:

> A node definition does not specify whether the node should be treated as a joint. Client implementations may wish to traverse the skins array first, marking each joint node.

> The skeleton property points to node that is the root of a joints hierarchy.

> A joint may have regular nodes attached to it, even a complete node sub graph with meshes. It's often used to have an entire geometry attached to a joint without having it being skinned by the joint. (ie. a sword attached to a hand joint).

This suggests to me that both of your files might be valid, even though `THREE.SkeletonHelper` cannot handle the second — three.js renders the model fine, but cannot display the debug information for the skeleton. But the spec could benefit from clarification on this point.

We've also discussed pulling the joint hierarchy out of the node tree entirely in some future version, or setting best practice that it should be a direct child of the scene root, and I don't know how those would affect your case. If marking these extra nodes as joints resolves the issue, I think that may be the most stable solution.

/cc @bghgary  @lexaknyazev

**Comment by donmccurdy** [comment]
Related: https://github.com/KhronosGroup/glTF/issues/1108

**Comment by Ziriax** [comment]
Thanks for the detailed info! I will consider a Maya2glTF flag to convert all skeleton nodes to joints, but indeed first the glTF 2.0 spec needs to be more specific about this. Personally I interpret the spec as joints being any subset of the nodes, a joint just refers to a node.

**Comment by Ziriax** [comment]
Maya2glTF author here. Too bad, but THREE.js existed before glTF 2.0, so understandable. Thanks for the effort.
