### ISSUE TITLE
Morph Targets interfere with each other

### ISSUE THREAD

**Issue by cainmartin** [donmccurdy/three-gltf-viewer#106]
I have a mesh that has been exported from Maya as FBX, then imported into Blender and re-exported as a gLTF file. I can import this into the viewer just fine (although for some reason I get two Morph folders (I don't think this is related to the issue).

So the second folder is the one that appears to be correctly bound to the morph target attributes. I can see the correct number, and when I slide them, the mesh deforms appropriately. However, there is a threshold where, once I have moved enough sliders, some of the sliders start affecting multiple attributes. And the attributes go from being smoothly animated, to snapping between two large values. 

Inspecting the attribute values - it appears as though only the one I modified with the slider was changed, yet I see two attributes change. I have attached the gltf files. 

This is what I see in gLTF viewer - if you move all the sliders hard right - then move the one that is highlighted red, you will see it snapping and modifying two attributes. It is not the only configuration of sliders that will cause this issue, but this is an easy repro case.

Moving everything back to zero returns individual slider behavior to normal (i.e. smooth movement, does not influence other attributes).

![mesh-issues](https://user-images.githubusercontent.com/7710239/44446398-a8bdad00-a61f-11e8-96e4-690ed7632e5f.PNG)

This is the raw exported gLTF files:

[soccer_head_7.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2309116/soccer_head_7.zip)

**Comment by donmccurdy** [comment]
The two morph folders are there because the mesh has two materials — each becomes a separate primitive and theoretically the morph targets could affect them separately, although in this case it seems the morph targets have no effect on the first.

The main issue you're seeing related to WebGL's [MAX_VERTEX_ATTRIBS](http://webglstats.com/webgl/parameter/MAX_VERTEX_ATTRIBS). For most devices, the hardware allows 16 vertex attributes,  which must be shared by vertex positions, normals, UVs, vertex colors, skinning, and morph targets. In practice that limits the number of morph targets that can be applied on the GPU. In three.js, the limit is set to:

- 4 morph positions + 4 morph normals
- OR 8 morph positions

Inactive morph influences don't count in three.js. This model contains both morph positions and normals, so when you enable a 5th morph target, one of the five will get disabled entirely. If the higher limit of 8 would be enough for you, you can disable export of morph normals in the Blender export settings.

**Comment by cainmartin** [comment]
Thank you very much for your response, that extremely helpful and makes a lot of sense. What are the implications of disabling the morph normals? I am looking to create a flat shaded result in the long term, would that have any implications on lighting do you think?

**Comment by donmccurdy** [comment]
Without morph normals you might see incorrect lighting on smooth shaded models, but if you're happy with a flat-shaded result then I don't think there's anything to worry about. You can disable export of both morph normals and the vertex normals themselves, to save space.

**Comment by cainmartin** [comment]
Perfect - thanks :)
