### ISSUE TITLE
Blendshapes does not quite work

### ISSUE THREAD

**Issue by enzyme69** [donmccurdy/three-gltf-viewer#108]
I tested a simple blendshape, shapekey animation on a simple animation made in Blender, it works fine:
[simpleanim.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2363049/simpleanim.zip)

However, when I tested with this head face shape with 51 blendshapes, the animation does not work. The blendshape/shapekeys information are there:

[HeadAnim.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2363048/HeadAnim.zip)

**Comment by donmccurdy** [comment]
See https://github.com/donmccurdy/three-gltf-viewer/issues/106 — I think this is the same issue. There are more than 16 morph targets active on the HeadAnim model. In this case only 4 will work at a time, because the model also uses morph normals. If you disable morph normals and morph tangents when exporting from Blender, you can raise that limit to 8. But in any case, no WebGL engine can support more than 16 morph targets on the GPU, engines would have to use (much slower) options of playing morph targets on the CPU instead. I don't know the limits of native engines, but I tried one and it didn't play correctly either.
