### ISSUE TITLE
Still Object progress event

### ISSUE THREAD

**Issue by Ghittone** [donmccurdy/three-gltf-viewer#110]
Good morning donmccurdy,
I've used your awesome glTF viewer (congrats!) to import a Blender animation.
It works fine on https://gltf-viewer.donmccurdy.com/ but there's no way to have it imported on Codepen through this code: <iframe src="https://gltf-viewer.donmccurdy.com#kiosk=true&amp;model=https://github.com/Ghittone/hello-world/blob/master/Groucho12.gltf" frameborder="0" width="600px" height="400px"></iframe>

Object progress event issue.

I'm just a rookie on this stuff but i'd really like to see it visualized on Codepen.

Thank you very much for your hard and awesome work.

alberto.

**Comment by donmccurdy** [comment]
Hi! You'll see the same error just going directly to that URL:

https://gltf-viewer.donmccurdy.com/#model=https://github.com/Ghittone/hello-world/blob/master/Groucho12.gltf

The problem is that the model needs to be hosted somewhere with CORS headers. GitHub Pages, Zeit Now, and https://surge.sh/ all are quick-ish ways to host your content. Also see: https://aframe.io/docs/0.8.0/introduction/hosting-and-publishing.html

**Comment by Ghittone** [comment]
Thanks a lot, donmccurdy!
Now it works perfectly and it is visualized even on Codepen (through Github Pages) here: https://codepen.io/Coderdo/pen/XxRzpJ

**Comment by donmccurdy** [comment]
Looks great! 😀
