### ISSUE TITLE
There is error when uploading glb when its Generator is Microsoft exporter by Microsoft

### ISSUE THREAD

**Issue by ghost** [donmccurdy/three-gltf-viewer#112]
The glb I tried to upload is the following, 
https://sketchfab.com/models/6d1f7e4dad7a4ac3931f6f39ceebed2c

I checked that its generator is Microsoft gltf exporter.
I found some other projects online that when they use three.js, they also have problems by showing this type of glb. 

I just wonder how this viewer can show the Microsoft gltf exporter glb file when it still has error. Thank you.

**Comment by donmccurdy** [comment]
For comparison:

| case | preview |
|---|---|
| sketchfab |  ![screen shot 2018-10-19 at 12 29 53 pm](https://user-images.githubusercontent.com/1848368/47239613-b16dfd80-d39a-11e8-9934-c1e8a7b8a65b.png) |
| three.js (generated) | ![screen shot 2018-10-19 at 12 30 13 pm](https://user-images.githubusercontent.com/1848368/47239630-bcc12900-d39a-11e8-9fd0-92be4a1f33dc.png) |
| three.js (original) | ![screen shot 2018-10-19 at 12 31 36 pm](https://user-images.githubusercontent.com/1848368/47239752-0873d280-d39b-11e8-921f-f8165bf1e97e.png)  |
| babylon (original) |  ![screen shot 2018-10-19 at 12 34 22 pm](https://user-images.githubusercontent.com/1848368/47239947-99e34480-d39b-11e8-8bb0-d437d0102b51.png) |
| babylon (generated) | ![screen shot 2018-10-19 at 12 36 51 pm](https://user-images.githubusercontent.com/1848368/47239974-b1223200-d39b-11e8-99bc-54ca684686ea.png) |

I'm afraid I don't know anything about the Microsoft exporter.. There is a spec/gloss texture and a metal/rough texture in the original, but not the sketchfab export, so those have been dropped along the way somewhere... what error or problems are you asking about here? The slight discoloration at the top of the model is probably from the spec/gloss map — is that intentional, or are you trying to get rid of it? Or are you just asking about the errors shown in the viewer's report, like: 

```

BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/0/bufferView
-- | -- | --
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/1/bufferView
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/2/bufferView
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/3/bufferView
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/4/bufferView
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/5/bufferView
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/6/bufferView
BUFFER_VIEW_TARGET_OVERRIDE | Override of previously set bufferView target or usage. Initial: 'VertexBuffer', new: 'Image'. | /images/7/bufferView
MESH_PRIMITIVE_ACCESSOR_WITHOUT_BYTESTRIDE | bufferView.byteStride must be defined when two or more accessors use the same buffer view. | /meshes/1/primitives/0/attributes/NORMAL
MESH_PRIMITIVE_ACCESSOR_WITHOUT_BYTESTRIDE | bufferView.byteStride must be defined when two or more accessors use the same buffer view. | /meshes/1/primitives/0/attributes/POSITION
MESH_PRIMITIVE_ACCESSOR_WITHOUT_BYTESTRIDE | bufferView.byteStride must be defined when two or more accessors use the same buffer view. | /meshes/1/primitives/0/attributes/TEXCOORD_0
```

/cc @bghgary

**Comment by lexaknyazev** [comment]
I remember these two validation issues from early versions of MS exporter. They should have been fixed already.
