### ISSUE TITLE
Implementing the loader as a basic webapp

### ISSUE THREAD

**Issue by ElChackAttack** [donmccurdy/three-gltf-viewer#139]
Hi Don,

I wanted to make a simple gltf viewer which would use the path from my assets folder to pick and select the desired 3D model. So instead of uploading anything, the options would come out of a dropdown and then they would be rendered accordingly.

Thanks,
Ricardo

**Comment by donmccurdy** [comment]
Hi @ElChackAttack – this code is open source precisely so that you can refer to or modify it. I can't necessarily help you with your project, but please feel free to use this code as a starting point. This threejs example may also be helpful to you: https://threejs.org/examples/?q=glt#webgl_loader_gltf_extensions

If you get stuck, I'd recommend http://discourse.threejs.org/ or Stack Overflow (https://stackoverflow.com/questions/tagged/three.js) as resources.

**Comment by ElChackAttack** [comment]
Awesome thanks!!!
