### ISSUE TITLE
GLB model is very shiny and cuts off some of the model.

### ISSUE THREAD

**Issue by markh777** [donmccurdy/three-gltf-viewer#141]
When I export a model to GLB format using FBX2glTF the model is very shiny, but moreover, part of the model cuts off when I pan to a certain position.

This does not happen in babylonjs viewer.

I'm using aframe.io to render the model and it happens there too.

Any help is greatly appreciated.

![gltf-viewer2](https://user-images.githubusercontent.com/48953952/55012873-15ce6200-4fb6-11e9-9a61-d1d156f685a4.png)
![babylonjs](https://user-images.githubusercontent.com/48953952/55012876-15ce6200-4fb6-11e9-9a07-30d95706013b.png)
![gltf-viewer](https://user-images.githubusercontent.com/48953952/55012877-15ce6200-4fb6-11e9-8340-751c97572832.png)

Any h

**Comment by donmccurdy** [comment]
I'll need access to the original FBX file to help debug this I think.

**Comment by zellski** [comment]
Please @ me if it turns out this is more of a FBX2glTF matter, or if I can help.

**Comment by markh777** [comment]
Attached is the original FBX, but no textures due to zip file size.

Thank you in advance.

[Mark2.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3009559/Mark2.zip)

**Comment by donmccurdy** [comment]
The shininess is inherent in the glTF file – it has metalness=0.4, roughness=0.4, which is probably not what a human figure should use. Overriding in threejs, something like this:

```js
content.traverse((o) => {
  if (!o.isMesh) return;
  o.material.roughness = 1;
  o.material.metalness = 0;
});
```

... will give a better result:

<img width="596" alt="Screen Shot 2019-03-27 at 8 50 09 AM" src="https://user-images.githubusercontent.com/1848368/55091037-5a690480-506d-11e9-9dd6-2aa5423ee2ea.png">

I'm not sure yet why the face is disappearing at certain angles. 😕

**Comment by zellski** [comment]
The model uses old-style Phong materials, which can't be easily converted to PBR. I had some more experimental code that tried to guess in the past, but it got weird. At this point, FBX2glTF just assigns some constant values. For a model like this, though, which is basically a scan (has real-world lighting baked into it), you might try the `--materials-unlit` flag, which has essentially the same effect as what @donmccurdy did above.

As for the broken polygons, I think something weird is going on with the model. This is from Autodesk's own FBX Review tool:
![image](https://user-images.githubusercontent.com/714167/55094127-02350100-5073-11e9-9b8f-fbecb2033ad2.png)

**Comment by zellski** [comment]
[Autodesk's online viewer](https://autode.sk/2JJiDbG) thinks the whole is down by the feet. 

![image](https://user-images.githubusercontent.com/714167/55094968-99e71f00-5074-11e9-978d-aae1bd17c87b.png)

**Comment by donmccurdy** [comment]
😱 Gotta love that face-melt effect.

That second screenshot explains the problem in threejs, then – the face mesh is located at the feet, and only renders in the correct place because of its skinning weights. ThreeJS does not take skinning into account when doing frustum culling (that is expensive), so the head disappears when the feet are out of the viewport, roughly speaking.

![Screen Shot 2019-03-27 at 9 52 00 AM](https://user-images.githubusercontent.com/1848368/55095808-ff87db00-5075-11e9-8e27-d5c627aab58e.png)
![Screen Shot 2019-03-27 at 9 52 02 AM](https://user-images.githubusercontent.com/1848368/55095810-00b90800-5076-11e9-82f2-f8951edb2616.png)

Maybe BabylonJS has a clever way of approximating frustum culling with skinning, but more likely they aren't culling in the sandbox viewer at all.

**Comment by bghgary** [comment]
@donmccurdy 
BabylonJS computes the bounding box for the skin once at load on the CPU which is why it works. Users are expected to manually refresh the bounding box if necessary. GPU skinning and bounding boxes has caused confusion for our users. This is actually why I wanted to chat with you during GDC but we never crossed paths.

**Comment by donmccurdy** [comment]
Ah sorry to have missed you! I suppose the same applies to morph targets.

> BabylonJS computes the bounding box for the skin once at load on the CPU which is why it works

So this would use the default pose, but not account for movement of the skeleton as one or more animations play?

**Comment by bghgary** [comment]
Right. You can manually update by calling a function.

**Comment by donmccurdy** [comment]
threejs has an option of recalculating bounding boxes manually, although I don't trigger it when playing animations in this viewer. I'd rather try to mostly keep things to the defaults or best practice. Not sure there's any more to do on this issue for this viewer, but let me know if there is.

**Comment by donmccurdy** [comment]
^Actually, recalculating the bounding box manually in threejs doesn't account for skinning yet, so that would be a fair feature request there too.
