### ISSUE TITLE
Cannot read property 'parser' of undefined

### ISSUE THREAD

**Issue by EtagiBI** [donmccurdy/three-gltf-viewer#146]
Hello,

When I try to load some models in the viewer, I get a browser dialog with "[object Event]" text. When I close this dialog the following error pops up:
![image](https://user-images.githubusercontent.com/20855725/56720449-4abc0900-675c-11e9-9944-085f7f8dae94.png)

Model example:
[Parser_Error.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3115892/Parser_Error.zip)

I thought there's something wrong with these models, but they load fine in Babylon viewer.

**Comment by donmccurdy** [comment]
It's a minor thing but the images entry here...

```
"images":[{"uri":"Archmodels59_%20leather.jpg"}]
```

...contains a URI-escaped space and doesn't strictly need to, per https://github.com/KhronosGroup/glTF/issues/1449.

@lexaknyazev @emackey do we have a preference, and should we suggest (but not require) that exporters encode _only_ reserved characters? This is the BabylonJS 3DS Max exporter.

In any case this viewer should accept the encoded form, so that's a bug.

**Comment by emackey** [comment]
No, I'm not sure that our suggestion would do any good, since URIs are allowed to contain those characters.  I actually like that the ecosystem has some `%20` models in it, so that we expose bugs like this.

Someday I'll add a test for this to the sample models...

**Comment by lexaknyazev** [comment]
FWIW, the model passes validation and its image URI is correct.
