### ISSUE TITLE
GLB animation wrong in Three.js viewer but correct in Babylon.js viewer

### ISSUE THREAD

**Issue by jhclaura** [donmccurdy/three-gltf-viewer#150]
Hi there, I have a glb file with simple rig, which animation runs well in [Babylonjs viewer](https://sandbox.babylonjs.com/) but not Three.js viewer. There's no error but a warning about no texture.

[finder_rig.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3196196/finder_rig.zip)
This is exported from Blender 2.8 with "Always Sample Animations" checked. And this is the
[blender file](https://github.com/donmccurdy/three-gltf-viewer/files/3196216/ani_test.zip) in case it would help.

Could anyone point me into direction about what might cause it, or any suggestions to fix it? 
Thanks!

**Comment by jak2030** [comment]
Hi! I am doing a basic Mixamo FBX --> Blender --> GLTF pipeline, and thought I was having issues on export, but it now seems that my files work fine in Babylon.js and in my own project, but animates very slowly in the glTF Viewer. Otherwise it seems everything is working as expected in glTF Viewer.

Here's the file...!

[alex-retry.glb.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3238817/alex-retry.glb.zip)

Let me know if I can supply anything else that might help.

**Comment by donmccurdy** [comment]
Thanks @jhclaura and @jak2030! Looking into this...

**Comment by donmccurdy** [comment]
This looks very similar to https://github.com/mrdoob/three.js/issues/16562 – even though the files are not working in this viewer, they should be OK in three.js itself. Not sure yet where the bug is in this viewer.

**Comment by donmccurdy** [comment]
Another example: https://github.com/mrdoob/three.js/files/3219932/rigify.zip

**Comment by donmccurdy** [comment]
And another: https://github.com/donmccurdy/three-gltf-viewer/files/3224007/simpleslide.zip
