### ISSUE TITLE
glb textures not displaying correctly

### ISSUE THREAD

**Issue by tjhanson** [donmccurdy/three-gltf-viewer#164]
I have a fairly large glb file (1.2gb) that is displaying textures incorrectly. It was exported from 3dsmax as a fbx, and converted to glb using facebook fbx2gltf. When i open it in windows 3dbuilder, it displays fine:
![image](https://user-images.githubusercontent.com/19607828/64982843-fa148c00-d873-11e9-81a6-e78b28fd39b5.png)
but when i try to display it online it looks like this:
![image](https://user-images.githubusercontent.com/19607828/64982890-17495a80-d874-11e9-91e0-fc83ef0812de.png)
file is available for download here: https://fullcirclethinking.com/ocgpmesh/meshes/ocgp_SINGLEmesh_190913.glb

**Comment by donmccurdy** [comment]
I'm going to venture a guess that you've maxed out WebGL texture memory on your device... 1 GB file pretty extreme for a web application. Do you have any smaller files that reproduce this issue?

**Comment by tjhanson** [comment]
no, but i have a larger file that doesn't do it. It takes about a minute to load but does display correctly. its 1.4gb, and the texture file is much larger. Both files are derived the same way using the same workflow, the difference being that the one incorrectly displaying is 10 projects merged into one fbx, while the other one is just one project. the one that doesnt display is 7 million polys, while the one that does display is 30 million polys.
displays correctly:
https://fullcirclethinking.com/miracosta/mesh/mesh.html
src file here:
https://fullcirclethinking.com/miracosta/mesh/meshes/MiraCostaOverall_Model_5.glb

**Comment by donmccurdy** [comment]
The size of the file and number of polygons are less important than the size of the textures here... keep in mind that depending on the level of compression, a JPG texture can inflate to ~8x size in uncompressed GPU memory, and plenty of modern GPUs have only 4GB of memory. You can improve things with textures in a GPU compression format like Basis, but (for now) you would not be able to embed them in the glTF file.

I don't have an internet connection sufficient to download these models and test them at the moment, but I'd suggest checking https://sandbox.babylonjs.com/ and https://threejs.org/editor/ as well, and see how the file compares.

This issue is unlikely to be specific to this viewer, I expect.
