### ISSUE TITLE
Exporting from Blender

### ISSUE THREAD

**Issue by NikLever** [donmccurdy/three-gltf-viewer#168]
Hi Don
I'm trying to get a good glb export from Blender. When I do I seem to get the camera fixed at 0,0,0. Making it very difficult to see the export in the viewer. I've tried to embed a camera but no joy. 
![Screenshot 2019-11-28 at 15 17 23](https://user-images.githubusercontent.com/47000827/69817315-3a887280-11f2-11ea-82fa-dad2c82e5845.png)
Any thoughts?
Cheers Nik
[fred4.glb.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3902249/fred4.glb.zip)

**Comment by donmccurdy** [comment]
It looks like the camera is embedded correctly, but this viewer shows its own camera by default. In the camera dropdown you can select your own:

<img width="1370" alt="Screen Shot 2019-11-28 at 11 16 09 AM" src="https://user-images.githubusercontent.com/1848368/69828441-bf629480-11d0-11ea-8aa2-e0e41192a7ba.png">

The default camera looks wrong in this case because it chooses a viewport without taking the skinning/animation into account. The skin scales the original mesh up quite a lot, which is why it's not visible in the default viewport.
