### ISSUE TITLE
There is a a problem with face culling in this model

### ISSUE THREAD

**Issue by danielmaciel** [donmccurdy/three-gltf-viewer#188]
Hi,

When loading this model on glTF viewer, I see the back-faces instead of front-faces.

https://sketchfab.com/3d-models/kalestra-the-sorceress-87637fba3f7c41d2bf23df2987185102

**Comment by donmccurdy** [comment]
The model looks identical (i.e. bad) when loaded into threejs, Babylonjs (https://sandbox.babylonjs.com/), and Blender, so this is a problem in the export from Sketchfab rather than the viewer.

Inspecting in Blender, the entire model has been set as transparent ("Alpha Blend"), which for a complex model like this, not designed for transparency, is going to cause all sorts of problems in realtime renderers. Might be worth filing a bug on Sketchfab, if they have such a thing, or asking in the forums?

If you just need to load the model in threejs, a quick fix would be:

```
model.traverse((o) => {
  if (o.isMesh) {
    o.material.transparent = false;
    o.material.depthWrite = true;
  }
});
```

^Of course, a few parts of the model really *are* supposed to be transparent, or at least `alphaTest > 0`, so you might want to do this piece by piece in Blender instead.
