### ISSUE TITLE
Works in your viewer, not in my sample project

### ISSUE THREAD

**Issue by wjf3** [donmccurdy/three-gltf-viewer#218]
Hey Don! Thanks so much for this awesome tool. However, I'm having some trouble getting my sample project to view the glb like it is in your viewer. It looks like the controls.target and camera position are spot on in your viewer but in my project they're set super far away and I can barely see the model floating by occasionally. Is this something you could ever help with? I'm sure it's something dumb I'm doing in my set-up. Thanks in advance!

[IJAHanger.zip](https://github.com/donmccurdy/three-gltf-viewer/files/5335113/IJAHanger.zip)

**Comment by wjf3** [comment]
Resolved with throwing some code at the wall and seeing what stuck :)

**Comment by Remraf23** [comment]
Hi @wjf3 are you able to share a code sample of how you fixed the problem? Thanks

**Comment by Remraf23** [comment]
> Hi @wjf3 are you able to share a code sample of how you fixed the problem? Thanks

Managed to sort this in the end. I was importing a gltf file into a react project and had the files in the wrong directory (I incorrectly had them in src, rather than public). I also had the camera zoomed too far out so when the model did eventually load it was not visible.

I also converted to a .glb file using `npx gltf pipeline` by using `npx gltf-pipeline -i scene.gltf -o scene.glb`
