### ISSUE TITLE
Errors faced while exporting to .glb from .blend

### ISSUE THREAD

**Issue by send2jithu** [donmccurdy/three-gltf-viewer#242]
Hi, so I have been trying to do some animations using **Blender** for a project of mine and tried to export the files in **.glb** file format but I have been getting some sort of random errors when I view these animations, like the components won't follow the required path or sometimes may be deformed. The problem here is that these errors are not exactly consistent meaning that trying to export multiple times just ends up giving different errors. 

Please find the attachments...these are some of the errors I find while trying to view the .glb file.

1. ![Screenshot 2021-02-12 163029](https://user-images.githubusercontent.com/64782545/107760443-bf0bd600-6d4f-11eb-8a5b-779d5a2f8601.jpg)

2. ![Screenshot 2021-02-12 163050](https://user-images.githubusercontent.com/64782545/107760445-c03d0300-6d4f-11eb-84d2-a73d5f06dcd5.jpg)

If you can help me out in any way it would be much appreciated. You can find the blend file I created and the exported glb file in the drive link below.

  https://drive.google.com/drive/folders/1KCFb-8UQ6Z48PFNJ8hG1g7I3Wjn6Ad4D?usp=sharing

**Comment by donmccurdy** [comment]
This looks much better, but still not fully correct, if you export it from a more recent version of Blender. I'd start by updating Blender.

After that though, you can test in both this viewer and sandbox.babylonjs.com/ to confirm that it's displaying the same way in both. Because both viewers get the same result, I think this is probably a bug in the Blender exporter, or the animation relies on some feature of Blender that cannot be exported to other software correctly. Either way, filing an issue on https://github.com/KhronosGroup/glTF-Blender-IO would be the next step to help debug that. Best of luck!

**Comment by send2jithu** [comment]
> This looks much better, but still not fully correct, if you export it from a more recent version of Blender. I'd start by updating Blender.
> 
> After that though, you can test in both this viewer and https://sandbox.babylonjs.com/ to confirm that it's displaying the same way in both. Because both viewers get the same result, I think this is probably a bug in the Blender exporter, or the animation relies on some feature of Blender that cannot be exported to other software correctly. Either way, filing an issue on https://github.com/KhronosGroup/glTF-Blender-IO would be the next step to help debug that. Best of luck!



Thanks for the help sir. Already tried different blender versions and also babylon.js viewer. Will look into the posting this in the link you shared.  I also feel like its not a bug in the viewer part but the exporting part.
