### ISSUE TITLE
A phenomenon in which transparent materials cannot be applied.

### ISSUE THREAD

**Issue by drop360** [donmccurdy/three-gltf-viewer#275]
A phenomenon in which transparent materials cannot be applied. I am using 3Ds max. In Max, transparency seems to be applied, but if you change the extension to gltf and pass it over, the transparency of the material is not applied. Are there any options that should be given separately?

**Comment by donmccurdy** [comment]
I don't know much about 3DS Max, but in most software there's more than one way to set up transparent materials, and not all of those may be supported by their exporters. If you're using the Babylon 3DS Max glTF exporter, this might be the documentation to check:

https://doc.babylonjs.com/extensions/Exporters/3DSMax_to_glTF#pbr-materials

I'd also recommend checking the model in a couple other viewers:

- https://gltf.report/
- https://sandbox.babylonjs.com/

If the transparency is consistently missing in two or more, the problem is presumably with the exporter process rather than the viewer.

If you need to tweak the model after exporting from 3DS Max, I would suggest Gestaltor or Blender (Alpha Mode = Alpha Blend) and that should export  back to glTF fine.
