### ISSUE TITLE
How does this repository solve the Z-fighting problem?

### ISSUE THREAD

**Issue by syzdev** [donmccurdy/three-gltf-viewer#300]
For the same model, there is a Z-fighting problem in the model after I use the native GLTFLoader, but there is no such problem after using this repository. After checking the source code, I didn't get any inspiration. Could you please describe the problem in detail. Thanks.

**Comment by donmccurdy** [comment]
Z-fighting occurs when triangles overlap, or are too close together for the amount of precision in your depth buffer. The depth buffer is configured by `camera.near` and `camera.far` properties. This viewer sets those properties automatically based on the input model — so that `.near` is as high as possible and `.far` is as low as possible, without clipping the model. Usually you can choose these properties based on the scale of your scene pretty quickly.

**Comment by syzdev** [comment]
@donmccurdy 

I tried to adjust the two parameters `camera.near` and `camera.far`, but when the value of `camera.near` is too large (e.g. from 0.1 to 10), when the camera is close to the model, the display of the model will be incomplete, and the Z-fighting problem has not been solved.

I am not sure whether there is something wrong with my code or other problems. I finally solved my Z-fighting problem by using `material.polygonOffset`.

**Comment by syzdev** [comment]
When solving the problem, I collected some information and share it below, hoping to be helpful to everyone.
- Use `camera.near` and `camera.far` parameters to solve the Z-fighting problem.
  - https://stackoverflow.com/questions/17786723/flickering-planes
  - https://stackoverflow.com/questions/21080619/three-js-webgl-large-spheres-appear-broken-at-intersection
- Other ways to solve the Z-fighting problem.
  - https://discourse.threejs.org/t/how-to-prevent-z-fighting-with-fake-shadows/27246/3
  - `logarithmicDepthBuffer`: https://threejs.org/examples/?q=DEPTH#webgl_camera_logarithmicdepthbuffer
