### ISSUE TITLE
glb model render error

### ISSUE THREAD

**Issue by neciszhang** [donmccurdy/three-gltf-viewer#333]
glb model : https://sketchfab.com/3d-models/female-thief-b244510c12f8420d8c3da7e9a426b5d6
When  I put it in gltf viewer.It's render
![image](https://user-images.githubusercontent.com/16221107/232685719-e216a4ca-b18f-4064-a6bf-536e9077a719.png)

**Comment by donmccurdy** [comment]
This models has two problems:

1. It uses the spec/gloss PBR workflow, which three.js no longer supports. You'll need to convert it to a metal/rough PBR workflow.
2. Every material on this model uses alpha blending, which is going to cause a lot of problems.

Both of these issues can be fixed by loading the model in https://gltf.report, clicking "OK" at the prompt to convert the materials, and then running the script below in the script tab:

```js
for (const material of document.getRoot().listMaterials()) {
	material.setAlphaMode('OPAQUE');
}
```

**Comment by neciszhang** [comment]
> 
Thanks a million!
