### ISSUE TITLE
Pluggable "Pipeline" Architecture?

### ISSUE THREAD

**Issue by zellski** [donmccurdy/three-gltf-viewer#72]
I'm musing a little over how I can most easily add drag-and-drop functionality to FBX2glTF, and of course my first instinct is to lean on someone else's hard work. More seriously, your viewer just feels like a great base interface on which to graft other glTF-related functionality.

So I was curious if you had at any time considered abstracting out the test for .{gltf, glb} suffix in DropHandler, and allowing external code to register file type handlers? I realise that with directory and zip file drops, there may be some non-obvious wrinkles.

In my ideal world, I'd just be able to receive a callback from your code saying "Uhh okay here's your .fbx file, do whatever with it." and then when conversion is complete (this is all given a local NPM setup where most things run in the browser, but FBX2lTF is available to call on the machine) toss back the glTF result to your viewer.

This is just a shot in the dark -- I expect you have many urges stronger than this one, if indeed this is an urge at all. But I figured I'd at least make sure this wasn't a direction you're pursuing at the moment. An alternative may be using the ?model= argument it appears you support, but to be frank I'm not sure exactly what kind of file/URL I could usefully send in there. Another alternative is to brutally fork this repo. We shall see!

**Comment by donmccurdy** [comment]
Good stuff to consider 👍

As it happens I've been wondering about a couple related things:

* making a multi-engine viewer (https://github.com/KhronosGroup/glTF/issues/1081)
* doing a glTF-Optimizer web tool
  * in the vein of glb-packer.glitch.me or [sbtron/makeglb](https://github.com/sbtron/makeglb), but with more stages of optimization like (1) merging meshes with shared materials, (2) stripping tangents, (3) Draco
* hosted converters for fbx2gltf, collada2gltf, obj2gltf, ...

I think those would all be great things to have, but (1) I haven't got the time to do all of them, and (2) even if I got PRs for it all, it feels like a lot of complexity to drop in here. E.g. I took a look through gltf.insimo.com and while it's awesome, I wouldn't take all that via PR because I'm worried I couldn't maintain it. Even just the converters would add a lot of build complexity.

So back to your question, what did you mean by "receive a callback"? Couple ideas...

1. change this from a static deployment to a Docker container, add a `converters/*` folder where arbitrary (probably node.js?) scripts can be dropped in that call fbx2gltf/collada2gltf/obj2gltf or whatever, then forking it becomes easy(ier), anyone can fork it for their own converters.
2. set up some UI-less APIs for fbx2gltf et al that accept files via POST, convert them, return results as a zip, and delete them ~24 hours later, and then just register each service with this viewer through some JSON registration:

```json
[
{
  "extension": ".fbx",
  "url": "fbx2gltf.now.sh/v1/"
},
{
  "extension": ".dae",
  "url": "collada2gltf.now.sh/v1/"
}
]
```

Gut reaction, I lean toward (2), and being able to rely on other people to deal with those format-specific containers. For example see [msdf-bmfont-web](https://github.com/donmccurdy/msdf-bmfont-web), using a Docker container on ZEIT Now to let users upload a font, convert it to an MSDF, then download the result. 

(and, fine with renaming this thing off `*.donmccurdy.com` if we're heading any of these directions)

**Comment by donmccurdy** [comment]
quick prototype of a hosted fbx2gltf api endpoint: https://github.com/donmccurdy/fbx2gltf-api

**Comment by zellski** [comment]
Wow, this is all a lot more than I had expected from a self-serving throw-away inquiry!

I concur with your assessment of gltf.insimo.com; it's amazing that it's there, but I am glad it's being maintained through someone **else's** blood, sweat and tears.

FBX2glTF actually comes with [a tiny API NPM](https://github.com/facebookincubator/FBX2glTF/tree/master/npm#usage) already. As for how execution would flow, I was deliberately vague; I am not sure which way the pieces would fit together best. Thinking about it now, architecturally I really like #2, the fully decoupled web service approach. It'd be an immense relief to just maintain that one endpoint with one specific job to do.

Unfortunately, as soon as I had the most basic FBX->glTF online conversion working, I would probably want to start adding custom UI. A real importer should really throw up an interstitial import dialog that contains a bunch of information extracted from the FBX, lets the user tweak the conversion parameters (i.e. the same as supplying command line arguments to the binary), and then hit Go. It's not super clear that UI integration can fit well with the #2 approach... or, at leat, it would no longer feel quite so low-hanging fruit?

**Comment by donmccurdy** [comment]
> A real importer should really throw up an interstitial import dialog that contains a bunch of information extracted from the FBX, lets the user tweak the conversion parameters (i.e. the same as supplying command line arguments to the binary), and then hit Go

Would the options shown in the UI require pre-loading the FBX file somehow? Or do you mean returning stats about the original FBX after converting to glTF? If options are fairly well-structured we could use the schema above:

```
{
  "extension": ".fbx",
  "url": "fbx2gltf.now.sh/v1/",
  "options": {
    "embed": {title: "Embed resources", type: Boolean, default: false},
    "binary": {title: "Binary", type: Boolean, default: false},
    "keep-attribute": {title: "Attributes", type: Array, default: [], options: ['POSITION', ...]}
  }
}
```

**Comment by zellski** [comment]
@donmccurdy Post-transformation stats could be nice, too, but it was configuration of the conversion parameter itself I meant. I had imagined that the FBX2glTF binary would run twice, under the hood -- first in an quick information-gathering-and-summarising sweep, to be parsed by the webapp, then after the user's had a chance to tweak settings, do the actual conversion and finally display the result in your viewer.

The idea of a configurable option widget UI hosted by three-gltf-viewer is tantalising! I don't want to just punt all the work onto you, but I will say it sounds like a great direction to move in, given your tripe-bullet-point ambition list above. Maybe could recruit another minion to help out. I'm probably going to be kind of consumed with FBX2glTF-specific work for a while.

In fact, I might throw together a simple UI-less "drag FBX in, get glTF file out" version first, with no preview -- just to placate the hordes, and give me time to work on this much more proper solution we're discussing here...

**Comment by donmccurdy** [comment]
Extracted my drag-and-drop code if that's helpful: https://www.npmjs.com/package/simple-dropzone

Adding UI to my viewer is much more appealing to me than adding a bunch of binaries needing to compile, run, and access disk space, so I'm certainly glad to do the UI end of that deal. 😅

**Comment by donmccurdy** [comment]
Hope you're doing well! No further plans here, but the following projects might be useful for similar things:

- https://github.com/donmccurdy/simple-dropzone
- https://github.com/donmccurdy/glTF-Transform
- https://modelviewer.dev/
