### ISSUE TITLE
Can't open model with texture

### ISSUE THREAD

**Issue by shenzhuxi** [donmccurdy/three-gltf-viewer#78]
I followed https://donmccurdy.com/2017/11/06/creating-animated-gltf-characters-with-mixamo-and-blender/ and can only make it work on three-gltf-viewer without texture exported. 
With Copy or Reference Images options for Kupoman glTF exporter, and I got these errors (It's working with Embed option). 

Validation report
Format: glTF 2.0
Generator: blendergltf v1.1.0
Draw calls: 1
Report generated by KhronosGroup/glTF-Validator 2.0.0-dev.1.7.

Errors
Code	Message	Pointer
FILE_NOT_FOUND	File not found. Node Exception: TypeError: Failed to fetch	/images/0
FILE_NOT_FOUND	File not found. Node Exception: TypeError: Failed to fetch	/images/1
FILE_NOT_FOUND	File not found. Node Exception: TypeError: Failed to fetch	/images/2
Info
Code	Message	Pointer
NODE_EMPTY	Empty node encountered.	/nodes/2
NODE_EMPTY	Empty node encountered.	/nodes/18
NODE_EMPTY	Empty node encountered.	/nodes/42

BTW, I got the same problem on BabylonJS viewer too.

**Comment by donmccurdy** [comment]
If the file has images, are you also dragging them into the viewer with the file? Since the error appears in multiple viewers, you may need to file an issue on the exporter or try it with KhronosGroup/glTF-Blender-Exporter: https://github.com/KhronosGroup/glTF-Blender-Exporter

**Comment by shenzhuxi** [comment]
I tried glTF-Blender-Exporter and it's fine with none embed images. 
After I disabled (didn't uninstall) glTF-Blender-Exporter and reinstalled Kupoman glTF exporter, I got more wired problem. 
I will created an issue on glTF-Blender-Exporter. 
Thanks.

**Comment by donmccurdy** [comment]
The export from KhronosGroup/glTF-Blender-Exporter looks correct to me:

![screen shot 2018-03-28 at 7 54 29 pm](https://user-images.githubusercontent.com/1848368/38067547-e3389926-32c1-11e8-822b-ae83be4f7cf5.png)

The FBX file contains three textures: diffuse, normal, and specular. glTF does not this type of specular map, so the specular texture is omitted. Perhaps it's possible to convert this model to the PBR textures used by glTF (metal/roughness or specular/glossiness) but that's more than I know how to do. :)

**Comment by florentpeyrard** [comment]
Hi,

I encountered a similar issue. I actually had no problem with "Eve" model (the same as in the previous comment) but there's a trick with "Remy" model. In Blender 2.79, for every material found in the outliner, it is necessary to switch PBR export alpha mode to "opaque" (Properties editor>Material>PBR export). This way, the model is displayed in gltf-viewer. 

However, I can't manage to get this model (Remy) displayed with A-FRAME in "webGL mode" (but it is correctly displayed if I click the "enter VR" button, so I'm pretty sure position/rotation/scale as long as light are OK). Any idea ? It's a rather big model : 63 MB with textures, I don't know if it can explain something.

By the way, thanks a lot @donmccurdy for your great work !

**Comment by donmccurdy** [comment]
@florentpeyrard if it works here it should be able to load in A-Frame, are you able to share a demo somehow?

**Comment by florentpeyrard** [comment]
Here are 2 small gifs showing both models, in gltf-viewer and A-Frame : 

![everunning](https://user-images.githubusercontent.com/15159900/43045049-9adc6eb4-8db1-11e8-88bd-00500cf120f2.gif)
![happyremy](https://user-images.githubusercontent.com/15159900/43045053-a8a92ad2-8db1-11e8-96da-96cd16520b33.gif)

Regarding Remy, assets are correctly downloaded and gltf-loader outputs as usual, with a loading time of 6-7 seconds. 

My A-Frame scene is defined as : 

```
					<a-scene embedded style="height: 600px; width: 90vw;"  light="defaultLightsEnabled: false">
						<a-entity position="0 10 0" rotation="-30 0 0" camera></a-entity>
						<a-entity :gltf-model="entityParams.path" id="entity"></a-entity>
						<a-light type="ambient" color="#FFF" position="-1 1 0"></a-light>
					</a-scene>
```

Remy's position is x: 0, y: -5, z: -10
Remy's rotation is x: 0, y: 180, z: 0
Remy's scale is x: 4, y: 4, z: 4
Those are applied through el.object3D.position.set / el.object3D.rotation.set / el.object3D.scale.set

**Comment by donmccurdy** [comment]
I don't have this Remy glTF model — if you can create a live demo or post the model somewhere I can debug that sooner, otherwise I can't reproduce the problem sorry. Also is it possible the camera is just looking away from the model, or looking out from the inside of it? Without `look-controls` in your example code that is possible, and happens often enough.

**Comment by florentpeyrard** [comment]
Remy is from Mixamo, as Eve in your comment on 29th of March :)

I tried to find Remy with look-controls but he's still invisible, and still gets visible when I switch to webVR.

**Comment by donmccurdy** [comment]
It may be a while before I have time to download these models, convert them to glTF, and set up an A-Frame scene to test. If you can provide any of this in addition to screenshots that would speed things along, thanks!

**Comment by donmccurdy** [comment]
I'm drawing a blank here, sorry. :( Even using the master version of A-Frame, which is the same version of three.js as my viewer, the textures are white. FWIW I would expect that the alpha mode on hair should be set to "Mask" in Blender, not "Opaque", but modifying things in A-Frame doesn't seem to be helping. Also weird that there are like 4 UV sets, but they seem to be mostly unused, so that's fine... Could you file a new bug on A-Frame? 

Also curious if you tried KhronosGroup/glTF-Blender-Exporter?

**Comment by florentpeyrard** [comment]
Hi @donmccurdy ,

thanks for the investigation. I tried with KhronosGroup/glTF-Blender-Exporter, the textures looked a bit better but still not ok (!). I'm sticking with Kupoman's glTF exporter for Blender, because with KhronosGroup/glTF-Blender-Exporter, if I don't unpack textures to files, I get path errors, so the workflow is a bit heavier.

I found out what is necessary to have textures displayed correctly in A-Frame : in Blender, for every material, tick Transparency, choose Z Transparency and set Alpha to 1. This works for every model I have tried so far.

Why the models were correctly displayed in gltf_viewer without tweaking this...is still a mystery to me.

**Comment by donmccurdy** [comment]
> with KhronosGroup/glTF-Blender-Exporter, if I don't unpack textures to files, I get path errors, so the workflow is a bit heavier.

Ah yeah we'll try to fix that (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/264). 

Glad it's working now, although I'm also confused. 😅
