### ISSUE TITLE
Animation is applied to the wrong node

### ISSUE THREAD

**Issue by chipweinberger** [donmccurdy/three-gltf-viewer#86]
Hey Don,

After some debugging, it appears the viewer is applying scale animation to the wrong node for this gltf file. It is supposed to be applied to the cube, but is instead applied to one of the spheres.

Note, if you control-f for "scale", only one node has the scale property set. 

I've included a photo of what it should look like (QTEK-clay-viewer).

test file:
[OctaneTest_GeometryGroupGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1900982/OctaneTest_GeometryGroupGltf.zip)

QTEK (correct - 7 spheres in a row with ground plane)
<img width="586" alt="test12" src="https://user-images.githubusercontent.com/1863934/38651208-c42170e6-3db4-11e8-9d78-15d364561320.PNG">

wrong: 
<img width="720" alt="test13" src="https://user-images.githubusercontent.com/1863934/38651289-43f9a82e-3db5-11e8-80d5-791446d7fa54.PNG">

**Comment by donmccurdy** [comment]
hi @chipweinberger — the issue appears to be one of duplicate node names in the glTF asset. This is perfectly fine per the specification, but the three.js animation system uses node names to bind animations, so duplicate names will cause misbindings. See https://github.com/donmccurdy/three-gltf-viewer/issues/58. I hope it will eventually be fixed in three.js, but it is a long-standing issue so you may want to work around it with unique names for now.

**Comment by chipweinberger** [comment]
Ah, I had a feeling that might be the cause

That's too bad about the work it will take to fix it properly. My gltf writer library faces a similar issue when buffer URI's are the same. For that, I increment a counter in the URI until it is unique. Perhaps you could implement something like too that as a easy hack.

I'll probably force it for name properties on my end too.

Best of luck.

**Comment by donmccurdy** [comment]
Will track in #58
