### ISSUE TITLE
lost animation in glb file from blender 

### ISSUE THREAD

**Issue by snowendless** [donmccurdy/three-gltf-viewer#93]
open the attached glb file in zip. we can see nothing until uncheck the animation.
[untitled.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1999985/untitled.zip)

**Comment by snowendless** [comment]
the blender version v2.78
exporter: https://github.com/KhronosGroup/glTF-Blender-Exporter v 2.0

**Comment by donmccurdy** [comment]
There is a problem in the animation data of the model:

![screen shot 2018-05-14 at 12 38 13 pm](https://user-images.githubusercontent.com/1848368/40019348-cf27270a-5773-11e8-956d-37d02085abd2.png)

I think this will need to be fixed in the Blender exporter. You can probably work around the issue by creating an additional keyframe for position/rotation/scale values.

**Comment by donmccurdy** [comment]
Filed to https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/234
